[package]
name = "traffic-rs"
version = "0.1.0"
authors = ["Alexander Rafferty <alexander.rafferty@manufacturingintelligence.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "*"
smallvec = "*"